DROP TABLE IF EXISTS trump_cards;

CREATE TABLE trump_cards (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID
    mark VARCHAR2(7),        -- マークの種類 (Spade, Heart, Diamond, Club)
    color VARCHAR2(5),       -- 色 (Black, Red)
    label VARCHAR2(5), -- 表記 (A, 2...9, 10, J, Q, K、JOKER)
    suji NUMBER(2), -- 数値
    is_num NUMBER(1)   -- 絵札か数字か (0:いいえ, 1:はい) ※J,Q,K,JKを絵札と定義
);

COMMENT ON COLUMN trump_cards.mark IS 'マークの種類';
COMMENT ON COLUMN trump_cards.color IS '色';
COMMENT ON COLUMN trump_cards.label IS '数字の表記';
COMMENT ON COLUMN trump_cards.suji IS '実際の数字';
COMMENT ON COLUMN trump_cards.is_num IS '数値フラグ(1:True, 0:False)';