INSERT INTO trump_cards
    (suji,label,mark,color,is_num)
VALUES
    -- スペードのカードデータ
    ('1','A','Spade','Black','0'),
    ('2','2','Spade','Black','1'),
    ('3','3','Spade','Black','1'),
    ('4','4','Spade','Black','1'),
    ('5','5','Spade','Black','1'),
    ('6','6','Spade','Black','1'),
    ('7','7','Spade','Black','1'),
    ('8','8','Spade','Black','1'),
    ('9','9','Spade','Black','1'),
    ('10','10','Spade','Black','1'),
    ('11','J','Spade','Black','0'),
    ('12','Q','Spade','Black','0'),
    ('13','K','Spade','Black','0'),
    -- クラブのカードデータ
    ('1','A','Club','Black','0'),
    ('2','2','Club','Black','1'),
    ('3','3','Club','Black','1'),
    ('4','4','Club','Black','1'),
    ('5','5','Club','Black','1'),
    ('6','6','Club','Black','1'),
    ('7','7','Club','Black','1'),
    ('8','8','Club','Black','1'),
    ('9','9','Club','Black','1'),
    ('10','10','Club','Black','1'),
    ('11','J','Club','Black','0'),
    ('12','Q','Club','Black','0'),
    ('13','K','Club','Black','0'),
    -- ハートのカードデータ
    ('1','A','Heart','Red','0'),
    ('2','2','Heart','Red','1'),
    ('3','3','Heart','Red','1'),
    ('4','4','Heart','Red','1'),
    ('5','5','Heart','Red','1'),
    ('6','6','Heart','Red','1'),
    ('7','7','Heart','Red','1'),
    ('8','8','Heart','Red','1'),
    ('9','9','Heart','Red','1'),
    ('10','10','Heart','Red','1'),
    ('11','J','Heart','Red','0'),
    ('12','Q','Heart','Red','0'),
    ('13','K','Heart','Red','0'),
    -- ダイヤのカードデータ
    ('1','A','Diamond','Red','0'),
    ('2','2','Diamond','Red','1'),
    ('3','3','Diamond','Red','1'),
    ('4','4','Diamond','Red','1'),
    ('5','5','Diamond','Red','1'),
    ('6','6','Diamond','Red','1'),
    ('7','7','Diamond','Red','1'),
    ('8','8','Diamond','Red','1'),
    ('9','9','Diamond','Red','1'),
    ('10','10','Diamond','Red','1'),
    ('11','J','Diamond','Red','0'),
    ('12','Q','Diamond','Red','0'),
    ('13','K','Diamond','Red','0'),
    -- ジョーカーカードデータ（数字とマークはなし）
    (-1, 'JOKER', 'JK','Black',0),
    (-1, 'JOKER', 'JK','Red',0);